# Default values for configmap-operator
replicaCount: 1

image:
  repository: yourusername/configmap-operator
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""
  annotations: {}

rbac:
  create: true

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {} 

serviceMonitor:
  enabled: false
  interval: 30s
  additionalLabels: {}
