apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "configmap-operator.fullname" . }}
  labels:
    {{- include "configmap-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "configmap-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "configmap-operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "configmap-operator.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 
