{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "configmap-operator.fullname" . }}
  labels:
    {{- include "configmap-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "configmap-operator.fullname" . }}
  labels:
    {{- include "configmap-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "configmap-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "configmap-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }} 
