apiVersion: v1
kind: Service
metadata:
  name: {{ include "configmap-operator.fullname" . }}-metrics
  labels:
    {{- include "configmap-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "configmap-operator.selectorLabels" . | nindent 4 }} 
