{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "configmap-operator.fullname" . }}
  labels:
    {{- include "configmap-operator.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: metrics
      interval: {{ .Values.serviceMonitor.interval }}
  selector:
    matchLabels:
      {{- include "configmap-operator.selectorLabels" . | nindent 6 }}
{{- end }} 
