name: Helm

on:
  push:
    branches: [ main ]
    paths:
      - 'helm-chart/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'helm-chart/**'

jobs:
  lint:
    name: Lint Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.0

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

  validate:
    name: Validate Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Validate Helm Chart
        run: |
          helm lint helm-chart/
          helm template helm-chart/ 
